name: Build and Release Flutter APK

on:
  workflow_dispatch:

jobs:
  build:
    name: Build Flutter APK
    runs-on: ubuntu-latest

    steps:
      - name: 拉取项目代码
        uses: actions/checkout@v4

      - name: 设置 Flutter 环境
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.2' # 根据你的 Flutter 版本修改

      - name: 获取依赖
        run: flutter pub get

      - name: 构建 APK
        run: flutter build apk --split-per-abi --no-tree-shake-icons

      - name: 上传 APK 到 Release (tag: test)
        uses: softprops/action-gh-release@v2
        with:
          tag_name: test                     # 必填，指定 tag
          name: Test Release                # Release 名称（可选）
          body: "自动构建上传 APK 文件"       # Release 描述（可选）
          generate_release_notes: true     # 自动生成 notes（可选）
          overwrite: true                  # 允许覆盖已有 tag
          files: build/app/outputs/flutter-apk/*.apk  # 上传文件路径
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

